config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :description, :address, :number_of_guests, :price_per_night, presence: true
  validates :number_of_guests, inclusion: { in: (1..20).to_a }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end


  private

  def flat_params
    params.require(:flat).permit(:name, :description, :address, :price_per_night, :number_of_guests)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :number_of_guests, collection: (1..20).to_a %>
  <%= f.input :price_per_night %>
  <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>
</div>

app/views/flats/edit.html.erb
<div class="container">
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :number_of_guests, collection: (1..20).to_a %>
  <%= f.input :price_per_night %>
  <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
<h1 class="m-3">All our Flats</h1>
<div class="d-flex justify-content-start">
<% @flats.each do |flat| %>
  <div class="card m-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">
        <%= flat.name %>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <%= flat.address %>
      </h6>
      <div class="d-flex">
        <p class="card-text mr-3">
          <i class=“fas fa-euro-sign”></i> <%= flat.price_per_night %>
        </p>
        <p class="card-text">
          <i class=“fas fa-user-friends”></i> <%= flat.number_of_guests %>
        </p>
      </div>
      <%= link_to 'More Info', flat_path(flat), class: "card-link" %> |
      <%= link_to 'Edit', edit_flat_path(flat), class: "card-link" %>
      <%# <a href="#" class="card-link">Card link</a> %>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<div class="container">
  <div class="title">
    <h1><%= @flat.name %></h1>
    <h2><%= @flat.address %></h2>
  </div>

  <div class="description">
    <p><%= @flat.description %></p>
  </div>

  <div class="details">
    <p><%= @flat.number_of_guests %></p>
    <p><%= @flat.price_per_night %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  </head>

  <body>
    <nav class="navbar navbar-light bg-secondary">
      <div class="container d-flex justify-content-between">
        <%= link_to "Airbnb Clone", flats_path, class: "navbar-brand" %>
        <%= link_to "New Flat", new_flat_path, class: "btn btn-primary" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>